"""initial

Revision ID: 052a0723c5ff
Revises: 61dd1885a0f6
Create Date: 2025-06-23 20:51:43.338819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052a0723c5ff'
down_revision = '61dd1885a0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logging',
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('error_timestamp', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=False),
    sa.Column('error_severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL'), nullable=False),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_table('user_accounts',
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('account_created_date', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('account_deleted_date', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_account_id')
    )
    op.create_table('login_details',
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.user_account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login_id')
    )
    with op.batch_alter_table('login_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_details_email_address'), ['email_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_details_username'), ['username'], unique=True)

    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('ticket_details', sa.Text(), nullable=False),
    sa.Column('issue_type', sa.Enum('incident', 'request', 'support', name='issuetype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='prioritytype'), nullable=False),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('ticket_summary', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'in_progress', name='statustype'), nullable=False),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.user_account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('ticket_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('comment_details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.user_account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_comments')
    op.drop_table('tickets')
    with op.batch_alter_table('login_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_details_username'))
        batch_op.drop_index(batch_op.f('ix_login_details_email_address'))

    op.drop_table('login_details')
    op.drop_table('user_accounts')
    op.drop_table('error_logging')
    # ### end Alembic commands ###
