"""Updated models

Revision ID: 2b9d1b338d88
Revises: a2af2ed8c55f
Create Date: 2025-06-08 16:19:57.413614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9d1b338d88'
down_revision = 'a2af2ed8c55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('isClosed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isClosed', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('closed_date')

    # ### end Alembic commands ###
