"""update ticket table

Revision ID: a2af2ed8c55f
Revises: 9b188a6430b2
Create Date: 2025-05-31 20:22:15.728979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2af2ed8c55f'
down_revision = '9b188a6430b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('open', 'closed', 'in_progress', name='statustype'), nullable=False))
        batch_op.add_column(sa.Column('needs_attention', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('needs_attention')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
