"""Remove error table

Revision ID: f35a848413b3
Revises: 2d42e7ca14ad
Create Date: 2025-06-26 18:58:34.233526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35a848413b3'
down_revision = '2d42e7ca14ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_logging')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('needs_attention')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_attention', sa.BOOLEAN(), nullable=False))

    op.create_table('error_logging',
    sa.Column('error_id', sa.INTEGER(), nullable=False),
    sa.Column('error_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=False),
    sa.Column('error_severity', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('error_id')
    )
    # ### end Alembic commands ###
