"""Initial commit

Revision ID: f37c595db2d7
Revises: 2b9d1b338d88
Create Date: 2025-06-08 16:39:40.148538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37c595db2d7'
down_revision = '2b9d1b338d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('closed_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('closed_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
